name: Publish documentation

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
         python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/Toloka/stubmaker/archive/refs/heads/main.zip
        pip install .
    - name: Checkout docs repository
      uses: actions/checkout@v3
      with:
        repository: 'Toloka/docs'
        path: 'docs-repo'
    - name: Generate markdowns
      run: |
        python ./misc/make_markdowns.py --module-root crowdkit --src-root crowdkit --output-dir docs/reference \
          --described-objects misc/described_objects_crowdkit.py \
          --github-source-url https://github.com/Toloka/crowd-kit/blob/${{ github.event.release.tag_name }}/crowdkit
        rm -r docs-repo/en/crowd-kit
        mv docs docs-repo/en/crowd-kit
    - name: Create Pull Request to docs repository
      uses: peter-evans/create-pull-request@v4
      with:
        path: 'docs-repo'
        commit-message: '[Autogenerated] markdowns for crowd-kit ${{ github.event.release.tag_name }} release'
        token: ${{ secrets.CI_PAT }}
        push-to-fork: toloka-ci-bot/docs
        title: 'crowd-kit release docs'
        body: 'This pull request contains autogenerated markdowns for crowd-kit ${{ github.event.release.tag_name }} release.'